### ISSUE TITLE
Plugin doesn't seem to work for 0.5 release of drone

### ISSUE THREAD

**Issue by schugh** [drone-plugins/drone-gcr#18]
Drone Version: 0.5 running on CoreOS

.drone.yml:

....
pipeline:
  build:
...
  publish:
    image: plugins/drone-gcr
    privileged: true
    registry: us.gcr.io
    repo: <my-repo>
    tag: latest
    storage_driver: overlay
    token: >
      ${GKE_SVC_ACCT}

Clone and build tasks run just fine.  Publish task fails with:

Drone GCR Plugin built from 8b60c0e
panic: EOF
goroutine 1 [running]:
panic(0x525e80, 0xc82000a0e0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/drone-plugins/drone-gcr/vendor/github.com/drone/drone-plugin-go/plugin.MustParse()
	/drone/src/github.com/drone-plugins/drone-gcr/vendor/github.com/drone/drone-plugin-go/plugin/param.go:129 +0x59
main.main()
	/drone/src/github.com/drone-plugins/drone-gcr/main.go:38 +0x47f

**Comment by schugh** [comment]
I created a working version of the drone-gcr plugin for Drone 0.5 from a fork.  The interface matches the original plugin.

[https://github.com/stayfari/drone-gcr]()

The plugin is built and on docker hub with handle **stayfari/drone-gcr**

I haven't tested it thoroughly but it should match the behavior of the original plugin with the exception of some additional error handling added as a good boy scout.
